--- #YAML:1.0
name:               Devel-SizeMe
version:            0.05
abstract:           ~
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Devel::Dwarn:    0
    HTML::Entities:  0
    JSON::XS:        0
    ORLite:          0
    perl:            5.005
    Test::More:      0
    XSLoader:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
